{
 "title": "Crossplane Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
   },
   { "name": "namespace", "query": "crossplane-system" },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "MR Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "First-Time-To-Reconcile",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "crossplane_managed_resource_first_time_to_reconcile_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "First-Time-To_Readiness",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "crossplane_managed_resource_first_time_to_readiness_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total MR Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(crossplane_managed_resource_exists)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synced MR Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(crossplane_managed_resource_synced)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synced False MR Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 17 },
   "targets": [
    {
     "expr": "sum(crossplane_managed_resource_exists) - sum(crossplane_managed_resource_synced)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready MR Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum(crossplane_managed_resource_ready)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready False MR Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(crossplane_managed_resource_exists) - sum(crossplane_managed_resource_ready)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synced MR Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(crossplane_managed_resource_synced)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synced False MR Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(crossplane_managed_resource_exists) - sum(crossplane_managed_resource_synced)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready MR Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(crossplane_managed_resource_ready)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready False MR Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(crossplane_managed_resource_exists) - sum(crossplane_managed_resource_ready)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time-to-Delete",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "crossplane_managed_resource_deletion_seconds_bucket\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drift Catch",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "crossplane_managed_resource_drift_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Control Plane Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Pods Running",
   "type": "heatmap",
   "description": "Host Cluster status of running pods. ",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum without(service, uid) (kube_pod_container_status_running{namespace=\"crossplane-system\"}) >= 1",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  }
 ]
}